force-app/main/default/objects/Opportunity2__c/Opportunity2__c.object-meta.xml
<CustomObject>
    <label>Opportunity2</label>
    <nameField>
        <label>NewOpp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity2__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity2__c/fields/Opportunity_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Id__c</fullName>
    <displayFormat>JO-{0000000}</displayFormat>
    <label>Opportunity Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity2__c/fields/Opportunity_Manager__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Manager__c</fullName>
    <label>Opportunity Manager</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity2__c/fields/Opportunity_Partner__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Partner__c</fullName>
    <label>Opportunity Partner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity2__c/fields/Sale_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sale_Stage__c</fullName>
    <label>Sale Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity2__c/fields/Service_Area__c.field-meta.xml
<CustomField>
    <fullName>Service_Area__c</fullName>
    <label>Service Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity2__c/fields/Service_Line__c.field-meta.xml
<CustomField>
    <fullName>Service_Line__c</fullName>
    <label>Service Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExcelTemp.cls
public with sharing class ExcelTemp {
    
    @AuraEnabled(cacheable=true)
    public static Opportunity2__c getAccountDataToExport(){
        Opportunity2__c Data = [Select Client_Name__c,
        Opportunity_Name__c,
        Opportunity_Partner__c,
        Opportunity_Manager__c,
         Created_On__c,
         Business__c ,
         Service_Area__c,
         Service_Line__c,
         Sale_Stage__c,
         Opportunity_Id__c from Opportunity2__c LIMIT 1];
        return Data;
    }
}