force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Student Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Father_Name__c.field-meta.xml
<CustomField>
    <fullName>Father_Name__c</fullName>
    <label>Father Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>II</fullName>
            </value>
            <value>
                <fullName>III</fullName>
            </value>
            <value>
                <fullName>IV</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>VI</fullName>
            </value>
            <value>
                <fullName>VII</fullName>
            </value>
            <value>
                <fullName>VIII</fullName>
            </value>
            <value>
                <fullName>IX</fullName>
            </value>
            <value>
                <fullName>X--slds-g-color-error-base-50</fullName>
                <color>#641CCF</color>
                <label>X</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/Mother_Name__c.field-meta.xml
<CustomField>
    <fullName>Mother_Name__c</fullName>
    <label>Mother Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Teacher__c/Student_Teacher__c.object-meta.xml
<CustomObject>
    <label>Student Teacher</label>
    <nameField>
        <displayFormat>STN-{00000}</displayFormat>
        <label>Student Teacher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Teacher</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Teacher__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Student Teacher</relationshipLabel>
    <relationshipName>Student_Teacher</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student_Teacher__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <label>Teacher</label>
    <referenceTo>Teacher__c</referenceTo>
    <relationshipLabel>Student Teacher</relationshipLabel>
    <relationshipName>Student_Teacher</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Teacher__c/Teacher__c.object-meta.xml
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Teacher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Teacher__c/fields/Subjects__c.field-meta.xml
<CustomField>
    <fullName>Subjects__c</fullName>
    <label>Subjects</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Arts</fullName>
            </value>
            <value>
                <fullName>Biology</fullName>
            </value>
            <value>
                <fullName>Chemistry</fullName>
            </value>
            <value>
                <fullName>Department</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Geography</fullName>
            </value>
            <value>
                <fullName>Hindi</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>Mathematics</fullName>
            </value>
            <value>
                <fullName>Music</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Teacher__c/fields/Teacher_Name__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Name__c</fullName>
    <label>Teacher Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SearchStudentController.cls
public with sharing class SearchStudentController {

    @AuraEnabled
    public static List<Student__c> getStudents(String queryString) {

        String studSearched =queryString +'%';
        
        List<Student__c> students_Name_matching = new List<Student__c>();
        students_Name_matching=[Select Student_Name__c,Father_Name__c,Mother_Name__c from Student__c where Student_Name__c LIKE :studSearched];
        return students_Name_matching;
    }
    

    @AuraEnabled
    public static Student__c getStudentDetails(Id studentId){
        Student__c studentDetailSearched=[Select Id,Student_Name__c,Level__c from Student__c where Id= :studentId];
        return studentDetailSearched;
    }

    @AuraEnabled
    public static List<Teacher__c> getTeacherOfStudent(Id studentId){
    
        List<Student_Teacher__c> relatedTeacher=[Select Teacher__c from Student_Teacher__c where Student__c= :studentId];
        List<Id> relatedTeacherId=new List<Id>();
        for(Student_Teacher__c i:relatedTeacher){
            relatedTeacherId.add(i.Teacher__c);
        }

        List<Teacher__c> relatedTeacherDetails=[Select Teacher_Name__c,Subjects__c from Teacher__c where Id In :relatedTeacherId ];
        return relatedTeacherDetails;
}



}