force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Student Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Father_Name__c.field-meta.xml
<CustomField>
    <fullName>Father_Name__c</fullName>
    <label>Father Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Father_s_occupation__c.field-meta.xml
<CustomField>
    <fullName>Father_s_occupation__c</fullName>
    <label>Father’s occupation</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Form_Submission_Date__c.field-meta.xml
<CustomField>
    <fullName>Form_Submission_Date__c</fullName>
    <label>Form Submission Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>II</fullName>
            </value>
            <value>
                <fullName>III</fullName>
            </value>
            <value>
                <fullName>IV</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>VI</fullName>
            </value>
            <value>
                <fullName>VII</fullName>
            </value>
            <value>
                <fullName>VIII</fullName>
            </value>
            <value>
                <fullName>IX</fullName>
            </value>
            <value>
                <fullName>X--slds-g-color-error-base-50</fullName>
                <color>#641CCF</color>
                <label>X</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/Mother_Name__c.field-meta.xml
<CustomField>
    <fullName>Mother_Name__c</fullName>
    <label>Mother Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Mother_s_occupation__c.field-meta.xml
<CustomField>
    <fullName>Mother_s_occupation__c</fullName>
    <label>Mother&apos;s occupation</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Student_Description__c.field-meta.xml
<CustomField>
    <fullName>Student_Description__c</fullName>
    <defaultValue>&quot;Hello&quot;</defaultValue>
    <label>Student Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Student_Teacher__c/Student_Teacher__c.object-meta.xml
<CustomObject>
    <label>Student Teacher</label>
    <nameField>
        <displayFormat>STN-{00000}</displayFormat>
        <label>Student Teacher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Teacher</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Teacher__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Student Teacher</relationshipLabel>
    <relationshipName>Student_Teacher</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student_Teacher__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <label>Teacher</label>
    <referenceTo>Teacher__c</referenceTo>
    <relationshipLabel>Student Teacher</relationshipLabel>
    <relationshipName>Student_Teacher</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Teacher__c/Teacher__c.object-meta.xml
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Teacher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Teacher__c/fields/Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Number__c</fullName>
    <label>Contact Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Teacher__c/fields/Joining_Date__c.field-meta.xml
<CustomField>
    <fullName>Joining_Date__c</fullName>
    <label>Joining Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Teacher__c/fields/Subjects__c.field-meta.xml
<CustomField>
    <fullName>Subjects__c</fullName>
    <label>Subjects</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Arts</fullName>
            </value>
            <value>
                <fullName>Biology</fullName>
            </value>
            <value>
                <fullName>Chemistry</fullName>
            </value>
            <value>
                <fullName>Department</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Geography</fullName>
            </value>
            <value>
                <fullName>Hindi</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>Mathematics</fullName>
            </value>
            <value>
                <fullName>Music</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Teacher__c/fields/Teacher_Name__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Name__c</fullName>
    <label>Teacher Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Teacher__c/fields/Teaching_Level__c.field-meta.xml
<CustomField>
    <fullName>Teaching_Level__c</fullName>
    <label>Teaching Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>II</fullName>
            </value>
            <value>
                <fullName>III</fullName>
            </value>
            <value>
                <fullName>IV</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>VI</fullName>
            </value>
            <value>
                <fullName>VII</fullName>
            </value>
            <value>
                <fullName>VIII</fullName>
            </value>
            <value>
                <fullName>IX</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/testTrigger.cls
@isTest
public class testTrigger {
    static testMethod void testTrigger() {
        // Create a test Teacher record
        Teacher__c testTeacher = new Teacher__c(Teacher_Name__c = 'Test Teacher 550',
            Teaching_Level__c = 'III',
            Contact_Number__c = 1234567890,
            Subjects__c = 'English',
            Joining_Date__c = date.parse('09/10/2023'));
        insert testTeacher;
		// Create a test Student record
        Student__c testStudent = new Student__c(Student_Name__c = 'Student 1', Level__c = 'III',
            Form_Submission_Date__c = date.parse('06/08/2023'),
            Student_Description__c = 'Hi', Father_Name__c = 'testing', Mother_Name__c = 'testing',
            Father_s_Occupation__c = 'X', Mother_s_Occupation__c = 'X', Contact_Email__c = 'abcd@gmail.com');
        insert testStudent;
		// Create a Student_Teacher__c record for the test Student and Teacher
        Student_Teacher__c existingAssignment = new Student_Teacher__c(
            Student__c = testStudent.Id,
            Teacher__c = testTeacher.Id
        );
        insert existingAssignment;
		// Create a new Student_Teacher__c record for the same Student and a different Teacher
        Teacher__c anotherTeacher = new Teacher__c(Teacher_Name__c = 'Test Teacher 551',
            Teaching_Level__c = 'III',
            Contact_Number__c = 1234567890,
            Subjects__c = 'English',
            Joining_Date__c = date.parse('01/10/2023'));
        insert anotherTeacher;
        Student_Teacher__c newAssignment = new Student_Teacher__c(
            Student__c = testStudent.Id,
            Teacher__c = anotherTeacher.Id
        );
        // Trigger the before insert/update event
        //DmlException e=new DmlException();
        String s;
        try {
            Test.startTest();
            insert newAssignment;
            Test.stopTest();
        } catch (DmlException e) {
            s = e.getMessage();
            System.debug('The following exception has occurred: ' + e.getMessage());
            //System.assertEquals(s,e.getMessage());
            //System.assert();
        }
        if(s !=NULL)
            System.assert(s.length() > 0, 'Error realtionship not added to new assignment');
        else
            System.assert(s==NULL, 'Error Relationship added to new assignment');

    }
}