force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Student Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>II</fullName>
            </value>
            <value>
                <fullName>III</fullName>
            </value>
            <value>
                <fullName>IV</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>VI</fullName>
            </value>
            <value>
                <fullName>VII</fullName>
            </value>
            <value>
                <fullName>VIII</fullName>
            </value>
            <value>
                <fullName>IX</fullName>
            </value>
            <value>
                <fullName>X--slds-g-color-error-base-50</fullName>
                <color>#641CCF</color>
                <label>X</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/Physically_disabled__c.field-meta.xml
<CustomField>
    <fullName>Physically_disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Physically disabled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Student_Description__c.field-meta.xml
<CustomField>
    <fullName>Student_Description__c</fullName>
    <defaultValue>&quot;Hello&quot;</defaultValue>
    <label>Student Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Student_Teacher__c/Student_Teacher__c.object-meta.xml
<CustomObject>
    <label>Student Teacher</label>
    <nameField>
        <displayFormat>STN-{00000}</displayFormat>
        <label>Student Teacher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Teacher</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Teacher__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Student Teacher</relationshipLabel>
    <relationshipName>Student_Teacher</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student_Teacher__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <label>Teacher</label>
    <referenceTo>Teacher__c</referenceTo>
    <relationshipLabel>Student Teacher</relationshipLabel>
    <relationshipName>Student_Teacher</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Teacher__c/Teacher__c.object-meta.xml
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Teacher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/StudentDetailsController.cls
public class StudentDetailsController {
  @AuraEnabled
    public static List<Student__c>getStudentsByTeacherId(Id teacherId) {
        List<Student__c> students = [SELECT Id, Name,Student_Name__c, Level__c, Physically_Disabled__c, Student_Description__c
                                     FROM Student__c
                                     WHERE Id IN(Select Student__c from Student_Teacher__c where Teacher__c =:teacherId)];
        return students;
    }
}